// frontend/src/components/AppShell.tsx
import { useState } from 'react'
import {
  AuditOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  LogoutOutlined,
  MailOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  SendOutlined,
  SettingOutlined,
} from '@ant-design/icons'
import { App, Avatar, Button, Layout, Menu, Space, Typography } from 'antd'
import { authApi } from '../api/client'
import type { User } from '../types'
import { DashboardPage } from '../pages/DashboardPage'
import { ResourcePage } from '../pages/ResourcePage'

const { Header, Sider, Content } = Layout

interface Props { user: User; onLogout: () => void }

// CHANGE [2026-08-30 12:58 +08:00] [WH400]: 用稳定应用壳承载角色化导航和响应式折叠，避免各页面重复布局状态。
export function AppShell({ user, onLogout }: Props) {
  const { message } = App.useApp()
  const [active, setActive] = useState('dashboard')
  const [collapsed, setCollapsed] = useState(false)
  const [mobile, setMobile] = useState(false)

  const items = [
    { key: 'dashboard', icon: <DashboardOutlined />, label: '工作台' },
    { key: 'orders', icon: <DatabaseOutlined />, label: '订单台账' },
    { key: 'shipments', icon: <SendOutlined />, label: '发货申请' },
    { key: 'inbox', icon: <MailOutlined />, label: '邮件收件箱' },
    { key: 'audit', icon: <AuditOutlined />, label: '操作日志' },
    ...(user.role === 'ADMIN' ? [{ key: 'settings', icon: <SettingOutlined />, label: '后台配置' }] : []),
  ]

  // CHANGE [2026-08-30 12:58 +08:00] [WH400]: 先清除服务端 Cookie 再释放本地用户状态，避免退出后仍可访问数据。
  const handleLogout = async () => {
    try { await authApi.logout() } finally { message.success('已安全退出'); onLogout() }
  }

  return (
    <Layout className="app-shell">
      {mobile && !collapsed ? <button className="sider-backdrop" aria-label="关闭导航菜单" onClick={() => setCollapsed(true)} /> : null}
      <Sider
        className={`app-sider${mobile ? ' is-mobile' : ''}`}
        width={216}
        collapsedWidth={mobile ? 0 : 72}
        collapsible
        collapsed={collapsed}
        trigger={null}
        breakpoint="lg"
        onBreakpoint={broken => { setMobile(broken); setCollapsed(broken) }}
      >
        <div className="sider-brand" aria-label="油品订单平台">
          <span className="header-drop" aria-hidden="true">滴</span>
          {collapsed ? null : <strong>油品订单平台</strong>}
        </div>
        <Menu mode="inline" selectedKeys={[active]} items={items} onClick={({ key }) => { setActive(key); if (mobile) setCollapsed(true) }} />
        <Button className="sider-toggle" type="text" icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />} aria-label={collapsed ? '展开导航菜单' : '收起导航菜单'} onClick={() => setCollapsed(value => !value)}>
          {collapsed ? null : '收起菜单'}
        </Button>
      </Sider>
      <Layout className="app-main">
        <Header className="app-header">
          <Button
            type="text"
            className="mobile-menu-button"
            icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
            aria-label={collapsed ? '展开导航菜单' : '收起导航菜单'}
            onClick={() => setCollapsed(value => !value)}
          />
          <Space size={12} className="header-profile">
            <Avatar size="small">{user.display_name.slice(0, 1)}</Avatar>
            <span className="header-identity">
              <Typography.Text className="header-user">{user.display_name}</Typography.Text>
              <Typography.Text className="header-role">{user.role === 'DEALER' ? '代理商' : '系统管理员'}</Typography.Text>
            </span>
            <Button type="text" className="header-action" icon={<LogoutOutlined />} aria-label="退出登录" onClick={handleLogout} />
          </Space>
        </Header>
        <Content className="app-content">
          {active === 'dashboard' ? <DashboardPage user={user} /> : <ResourcePage resource={active} user={user} />}
        </Content>
      </Layout>
    </Layout>
  )
}

// frontend/src/components/AppShell.vue
<script setup lang="ts">
import { computed, defineAsyncComponent, ref } from 'vue'
import {
  App,
  Avatar as AAvatar,
  Button as AButton,
  Layout as ALayout,
  LayoutSider as ALayoutSider,
  LayoutHeader as ALayoutHeader,
  LayoutContent as ALayoutContent,
  Menu as AMenu,
  MenuItem as AMenuItem,
  Space as ASpace,
  TypographyText as ATypographyText,
} from 'ant-design-vue'
import {
  AuditOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  LogoutOutlined,
  MailOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  SendOutlined,
  SettingOutlined,
} from '@ant-design/icons-vue'
import { authApi } from '../api/client'
import type { User } from '../types'
import DashboardPage from '../pages/DashboardPage.vue'
const ResourcePage = defineAsyncComponent(() => import('../pages/ResourcePage.vue'))
const AdminSettingsPage = defineAsyncComponent(() => import('../pages/AdminSettingsPage.vue'))

const props = defineProps<{ user: User }>()
const emit = defineEmits<{ logout: [] }>()
const { message } = App.useApp()
const active = ref('dashboard')
const collapsed = ref(false)
const mobile = ref(false)
const loggingOut = ref(false)
const roleLabel = computed(() => ({ ADMIN: '系统管理员', SALES: '零件销售', DEALER: '代理商' })[props.user.role])
const items = computed(() => [
  { key: 'dashboard', icon: DashboardOutlined, label: '工作台' },
  { key: 'orders', icon: DatabaseOutlined, label: '订单台账' },
  { key: 'shipments', icon: SendOutlined, label: '发货申请' },
  { key: 'inbox', icon: MailOutlined, label: '邮件收件箱' },
  { key: 'audit', icon: AuditOutlined, label: '操作日志' },
  ...(props.user.role === 'ADMIN' ? [{ key: 'settings', icon: SettingOutlined, label: '后台配置' }] : []),
])
function navigate(key: string) {
  if (key === 'settings' && props.user.role !== 'ADMIN') return
  active.value = key
  if (mobile.value) collapsed.value = true
}
function breakpoint(broken: boolean) {
  mobile.value = broken
  collapsed.value = broken
}
async function logout() {
  if (loggingOut.value) return
  loggingOut.value = true
  try {
    await authApi.logout()
    message.success('已安全退出')
    emit('logout')
  } catch (error) {
    message.error(error instanceof Error ? error.message : '退出失败，请重试')
  } finally {
    loggingOut.value = false
  }
}
</script>

<template>
  <a-layout class="app-shell">
    <button v-if="mobile && !collapsed" class="sider-backdrop" aria-label="关闭导航菜单" @click="collapsed = true" />
    <a-layout-sider
      v-model:collapsed="collapsed"
      class="app-sider"
      :class="{ 'is-mobile': mobile }"
      :width="216"
      :collapsed-width="mobile ? 0 : 72"
      collapsible
      :trigger="null"
      breakpoint="lg"
      @breakpoint="breakpoint"
    >
      <div class="sider-brand" aria-label="油品订单平台">
        <span class="header-drop" aria-hidden="true">滴</span><strong v-if="!collapsed">油品订单平台</strong>
      </div>
      <a-menu mode="inline" :selected-keys="[active]">
        <a-menu-item v-for="item in items" :key="item.key" @click="navigate(item.key)"
          ><template #icon><component :is="item.icon" /></template>{{ item.label }}</a-menu-item
        >
      </a-menu>
      <a-button
        class="sider-toggle"
        type="text"
        :aria-label="collapsed ? '展开导航菜单' : '收起导航菜单'"
        @click="collapsed = !collapsed"
        ><template #icon><MenuUnfoldOutlined v-if="collapsed" /><MenuFoldOutlined v-else /></template
        ><template v-if="!collapsed">收起菜单</template></a-button
      >
    </a-layout-sider>
    <a-layout class="app-main">
      <a-layout-header class="app-header">
        <a-button
          type="text"
          class="mobile-menu-button"
          :aria-label="collapsed ? '展开导航菜单' : '收起导航菜单'"
          @click="collapsed = !collapsed"
          ><template #icon><MenuUnfoldOutlined v-if="collapsed" /><MenuFoldOutlined v-else /></template
        ></a-button>
        <a-space :size="12" class="header-profile"
          ><a-avatar size="small">{{ user.display_name.slice(0, 1) }}</a-avatar
          ><span class="header-identity"
            ><a-typography-text class="header-user">{{ user.display_name }}</a-typography-text
            ><a-typography-text class="header-role">{{ roleLabel }}</a-typography-text></span
          ><a-button type="text" class="header-action" aria-label="退出登录" :loading="loggingOut" @click="logout"
            ><template #icon><LogoutOutlined /></template></a-button
        ></a-space>
      </a-layout-header>
      <a-layout-content class="app-content">
        <DashboardPage v-if="active === 'dashboard'" :user="user" @navigate="navigate" />
        <AdminSettingsPage v-else-if="active === 'settings' && user.role === 'ADMIN'" :user="user" />
        <ResourcePage v-else :key="active" :resource="active" :user="user" />
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>
