// frontend/src/pages/LoginPage.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'
import {
  App,
  Button as AButton,
  Form as AForm,
  FormItem as AFormItem,
  Input as AInput,
  InputPassword as AInputPassword,
} from 'ant-design-vue'
import { LockOutlined, SafetyCertificateOutlined, UserOutlined } from '@ant-design/icons-vue'
import { authApi } from '../api/client'
import type { User } from '../types'

const emit = defineEmits<{ success: [user: User] }>()
const { message } = App.useApp()
const form = reactive({ email: '', password: '' })
const submitting = ref(false)
async function login() {
  if (submitting.value) return
  submitting.value = true
  try {
    emit('success', await authApi.login(form.email, form.password))
  } catch (error) {
    message.error(error instanceof Error ? error.message : '登录失败，请检查账号和密码')
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <main class="login-page">
    <div class="login-shell">
      <section class="login-visual" aria-label="平台介绍">
        <img
          class="login-visual-image"
          src="/images/login-operations-3d.webp?v=20260901-hd"
          alt="仓库、配送车辆、订单单据与业务节点组成的协同场景"
        />
      </section>
      <section class="login-panel" aria-labelledby="login-title">
        <span class="login-brand-mark" aria-hidden="true">K</span>
        <div class="login-heading">
          <h1 id="login-title">登录</h1>
          <p>欢迎登录油品订单协同平台</p>
        </div>
        <a-form class="login-form" :model="form" layout="vertical" size="large" :required-mark="false" @finish="login">
          <a-form-item name="email" :rules="[{ required: true, message: '请输入账号' }]">
            <a-input
              v-model:value="form.email"
              placeholder="请输入账号或邮箱"
              aria-label="账号"
              autocomplete="username"
              autofocus
              ><template #prefix><UserOutlined /></template
            ></a-input>
          </a-form-item>
          <a-form-item name="password" :rules="[{ required: true, message: '请输入密码' }]">
            <a-input-password
              v-model:value="form.password"
              placeholder="请输入密码"
              aria-label="密码"
              autocomplete="current-password"
              ><template #prefix><LockOutlined /></template
            ></a-input-password>
          </a-form-item>
          <a-button class="login-submit" type="primary" html-type="submit" :loading="submitting">立即登录</a-button>
        </a-form>
        <div class="login-security-note">
          <SafetyCertificateOutlined aria-hidden="true" /><span>仅限已授权账号访问，连接信息已加密保护</span>
        </div>
      </section>
    </div>
    <p class="login-copyright">© 2026 KK Hub · 油品订单协同平台</p>
  </main>
</template>

// frontend/src/pages/LoginPage.tsx
import { LockOutlined, MailOutlined } from '@ant-design/icons'
import { App, Button, Form, Input } from 'antd'
import { authApi } from '../api/client'
import type { User } from '../types'

interface Props { onSuccess: (user: User) => void }

// CHANGE [2026-08-30 12:58 +08:00] [WH400]: 提供统一邮箱密码入口，并将错误限制在登录表单内反馈。
export function LoginPage({ onSuccess }: Props) {
  const { message } = App.useApp()

  // CHANGE [2026-08-30 12:58 +08:00] [WH400]: 登录失败留在当前表单提示，成功后才进入业务页面。
  const handleFinish = async (values: { email: string; password: string }) => {
    try {
      onSuccess(await authApi.login(values.email, values.password))
    } catch (error) {
      message.error(error instanceof Error ? error.message : '登录失败')
    }
  }

  return (
    <main className="login-page">
      <section className="login-panel" aria-labelledby="login-title">
        <div className="brand-mark" aria-hidden="true">滴</div>
        <h1 id="login-title">油品发货核销平台</h1>
        <p>订单余额、分批发货与操作记录统一管理</p>
        <Form layout="vertical" size="large" onFinish={handleFinish} requiredMark={false}>
          <Form.Item label="邮箱" name="email" rules={[{ required: true, type: 'email', message: '请输入有效邮箱' }]}>
            <Input prefix={<MailOutlined />} placeholder="name@example.com" autoComplete="email" />
          </Form.Item>
          <Form.Item label="密码" name="password" rules={[{ required: true, message: '请输入密码' }]}>
            <Input.Password prefix={<LockOutlined />} placeholder="请输入密码" autoComplete="current-password" />
          </Form.Item>
          <Button type="primary" htmlType="submit" block>登录</Button>
        </Form>
      </section>
    </main>
  )
}
